name: aarch64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
jobs:
  ubuntu-latest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: uraimo/run-on-arch-action@v2
      name: Build and Run Tests
      with:
        arch: aarch64
        distro: ubuntu_latest
        dockerRunArgs: |
          --privileged
        install: |
          export CARGO_TERM_COLOR=always
          export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
          apt-get update && apt-get install -y gdb pip curl python3.10-dev clang llvm build-essential
          curl https://sh.rustup.rs -o rustup.sh && chmod +x rustup.sh && \
          ./rustup.sh -y && rm rustup.sh
        run: |
          export PATH=/root/.cargo/bin:$PATH
          export CARGO_TERM_COLOR=always
          export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
          cargo build --all-features --release --verbose
          cargo test --release --verbose
